extends:
  - 'react-app'
  - 'airbnb-base'
rules:
  semi:
    - error
    - never
  indent:
    - error
    - 4
    - SwitchCase: 1
  import/no-unresolved: off
  no-shadow: off
  operator-linebreak:
    - error
    - after
    - overrides:
        ?: ignore
        ':': ignore
  comma-dangle:
    - error
    - only-multiline
  no-underscore-dangle: off
  object-curly-newline: off
  arrow-parens:
    - error
    - always
  max-len:
    - error
    - code: 200
  linebreak-style: 0
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-unused-vars:
    - error
    - varsIgnorePattern: '^(styles)$'
      argsIgnorePattern: '^(props|dispatch|state)$'
  no-param-reassign: off
  no-plusplus: off
  class-methods-use-this:
    - error
    - exceptMethods: ['render']
  no-console: 'off'